AllCops:
  TargetRubyVersion: 3.1
  DisplayCopNames: true
  DisplayStyleGuide: true
  SuggestExtensions: false
  NewCops: disable

  Exclude:
    - 'bin/*'

Layout/LineLength:
  Max: 100

Style/GlobalStdStream:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Security/Open:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'spec/factories/*.rb'
    - '*.gemspec'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Max: 40
